services:
  apache:
    build: .
    container_name: lamp-apache
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./apache-config:/etc/apache2/sites-available
    depends_on:
      - mariadb
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000

  mariadb:
    image: mariadb:10.6
    container_name: lamp-mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: lamp-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - mariadb

volumes:
  db_data:
    driver: local
