name: Auto Release

on:
  push:
    tags:
      - 'v*'  # Automatically triggers on tag pushes
  workflow_dispatch:  # Allow manual triggering

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
